### ISSUE TITLE
bug: the supply chain phases on a phone are not continuous scroll

### ISSUE THREAD

**Issue by carolinewoolard** [blerchin/bfamfaphd-website#23] opened 2016-07-26 19:52 UTC
When I click on encounter, I am stuck in the encounter section of the text, and do no scroll to the next phase automatically.

**Comment by blerchin** [comment] 2016-07-28 05:58
duplicate of https://github.com/blerchin/bfamfaphd-website/issues/12

**Closed as completed by blerchin** 2016-07-28 05:58 UTC
